# Generated by Django 4.2 on 2023-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0002_car_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='email',
        ),
        migrations.AddField(
            model_name='car',
            name='car_description',
            field=models.TextField(null=True),
        ),
    ]
