# Generated by Django 4.2 on 2023-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0003_remove_car_email_car_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
