# Generated by Django 4.2 on 2023-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0005_car_image_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
